part of './app_pages.dart';

abstract class Routes {
  static const home = '/home';
  static const homeAdmin = '/homeAdmin';
  static const casterManager = '/casterManager';
  static const guestManager = '/guestManager';
  static const chatManager = '/chatManager';
  static const castPaymentManager = '/castPaymentManager';
  static const callList = '/callList';
  static const homeFemale = '/homeFemale';
  static const error = '/error';
  static const search = '/search';
  static const message = '/message';
  static const call = '/call';
  static const callFemale = '/call_female';
  static const myPage = '/my-page';
  static const myPageFemale = '/my-page-female';
  static const searchDetail = '/search_detail';
  static const editProfile = '/editProfile';
  static const login = '/login';
  static const userDetail = '/userDetail/';
  static const messageDetail = '/messageDetail/';
  static const pointHistory = '/pointHistory';
  static const pointHistoryFemale = '/pointHistoryFemale';
  static const paymentInformation = '/paymentInformation';
  static const saleProceed = '/saleProceed';
  static const transferInformation = '/transferInformation';
  static const instantDeposit = '/instantDeposit';
  static const userGuide = '/userGuide';
  static const userGuideFemale = '/userGuideFemale';
  static const help = '/help';
  static const helpFemale = '/helpFemale';
  static const selectMood = '/selectMood';
  static const firstTimeUser = '/firstTimeUser';
  static const confirmCall = '/confirmCall';
  static const purchasePoint = '/purchasePoint';
  static const term = '/term';
  static const law = '/law';
  static const privacyPolicy = '/privacyPolicy';
  static const searchCall = '/searchCall/';
  static const ticketDetail = '/ticketDetail/';
}
